### ISSUE TITLE
Wrong arguemnt name for the assess function

### ISSUE THREAD

**Issue by bassam-abulnoor** [Sam-Osian/GroupThink#2]
Hello Sir,
For the assess function the argument is called (df), but within the code, it's given the name (data); this causes the error Error as in 

UseMethod("pivot_longer"):  no applicable method for 'pivot_longer' applied to an object of class "function" 

Because "data" is considered the function, not the "df" argument. 
Thanks for your efforts

**Comment by Samuel-Osian-Andrews** [comment]
Hi, @bassam-abulnoor ! Thank you very much for reporting this issue.

As you point out, it looks like the problem was caused by incorrect parameter mapping in the `assess()` function. I've made some changes and it now appears to function correctly. Could you kindly let me know if everything works correctly your end?

**Comment by bassam-abulnoor** [comment]
Yes it works now thank you
